title: "NetDevTechBytes"
description: "Tech blogs on Networking, Coding Patterns, and More."
url: "https://netdevtechbytes.github.io"
baseurl: ""
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "Blog"
    url: "/blog/"
  - title: "Coding"
    url: "/leetcode/"
  - title: "Networking"
    url: "/networking/"

# Author    
author:
  name: "Your Name"
  bio: "Network Engineer & Tech Enthusiast | Solving problems through code."
  location: "Global"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/netdevtechbytes"

# Collections
collections:
  pages:
    output: true
    permalink: /:path/

# Defaults
defaults:
  - scope:
      path: "leetcode"
      type: "pages"
    values:
      layout: single

