title: "NetDevTechBytes"
description: "Tech blogs on Networking, Coding Patterns, and More."
url: "https://netdevtech.github.io"
baseurl: ""
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
